### ISSUE TITLE
Intent with respect to liboqs-rust?

### ISSUE THREAD

**Issue by jac-cbi** [sentclose/liboqs-rust#2]
Hi!  Thanks for opening up issues on this repo, much appreciated. 

As I mentioned in my issue for [`liboqs-rust` 269](https://github.com/open-quantum-safe/liboqs-rust/issues/269), I'm in the early stages of writing a rust library which requires both ML-KEM (FIPS), and Kyber (non-fips).  I've started with `safe-oqs` for two simple reasons: 1) it has a more recent `liboqs` which contains ML-KEM, and 2) it's published on crates.io.  

afaict, there are only two differences between `safe-oqs` and `liboqs-rust`. 

1) newer version of `liboqs`, which includes ML-KEM, ML-DSA

2) Exposes both to Rust users.

The rest of the diff is just renaming the library.

In the big picture, openssl has incorporated liboqs into their repo, and so there is yet another path for end users, particularly FIPS users to use PQ crypto from Rust.

Which leads to my main question:  What is the purpose of `safe-oqs`?  It provides no extra "safety" over its upstream code.  Did attempts to upstream changes for `ML-KEM` and `ML-DSA` to liboqs-rust fail?

**Comment by joernheinemann** [comment]
Hello @jac-cbi 

The current version of [liboqs ](https://github.com/open-quantum-safe/liboqs-rust) is not secure anymore. There was a timing attack against kyber where you could get the secret key. This is fixed in this version of oqs that im using (version 0.10.1 of the c impl: https://github.com/Open-Quantum-Safe/liboqs/tree/5dd87dcaafa6f90e983ef464f9f6a75f9485fb26)

**Comment by jac-cbi** [comment]
Ok, I see that now.  I just did a diff between the two repos and that didn't show the diff of liboqs.  I assumed the liboqs bump was just to pull in ML-KEM / ML-DSA.  My bad.
